const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),os=require('os');
const PORT=process.env.PORT||8000,PUBLIC=path.join(__dirname,'public'),clients=new Set(),animals=[];
const sendJson=(res,code,obj)=>{const body=JSON.stringify(obj);res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store'});res.end(body)};
const type=f=>({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'})[path.extname(f).toLowerCase()]||'application/octet-stream';
const broadcast=(event,payload)=>{const msg=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const r of clients){try{r.write(msg)}catch{clients.delete(r)}}};
http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);
 if(req.method==='GET'&&u.pathname==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(': connected\n\n');clients.add(res);req.on('close',()=>clients.delete(res));return}
 if(req.method==='GET'&&u.pathname==='/api/animals')return sendJson(res,200,animals.slice(-20));
 if(req.method==='POST'&&u.pathname==='/api/animals'){let b='';req.on('data',c=>{b+=c;if(b.length>5_000_000)req.destroy()});req.on('end',()=>{try{const d=JSON.parse(b);if(d.species!=='lion'||typeof d.texture!=='string'||!d.texture.startsWith('data:image/png;base64,'))return sendJson(res,400,{error:'Bad payload'});const a={id:crypto.randomUUID(),species:'lion',texture:d.texture,createdAt:Date.now()};animals.push(a);while(animals.length>30)animals.shift();broadcast('animal',a);sendJson(res,201,{ok:true,id:a.id})}catch(e){sendJson(res,400,{error:e.message})}});return}
 if(req.method==='POST'&&u.pathname==='/api/clear'){animals.length=0;broadcast('clear',{});return sendJson(res,200,{ok:true})}
 if(req.method==='GET'){let clean=decodeURIComponent(u.pathname).replace(/^\/+/,''),f=path.normalize(path.join(PUBLIC,clean||'index.html'));if(!f.startsWith(PUBLIC)){res.writeHead(403);return res.end('Forbidden')}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');return fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':type(f),'Cache-Control':f.endsWith('.html')?'no-store':'public, max-age=300'});res.end(d)})}
 res.writeHead(405);res.end('Method not allowed');
}).listen(PORT,'0.0.0.0',()=>{console.log(`Live Sketchbook V0: http://localhost:${PORT}`);try{for(const list of Object.values(os.networkInterfaces()))for(const n of list||[])if(n.family==='IPv4'&&!n.internal)console.log(`LAN: http://${n.address}:${PORT}`)}catch(e){console.warn(`LAN address unavailable: ${e.message}`)}});
